services:
  turkiyefinans:
    container_name: turkiyefinansapp
    image: turkiyefinans
    build:
      context: .
      dockerfile: ././TurkiyeFinans/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=TurkiyeFinansDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - mssql
    networks:
      - turkiyefinansnet 

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_ENCRYPT: Optional
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - mssqldata:/var/opt/mssql    
    networks:
      - turkiyefinansnet

volumes:
  mssqldata:

networks:
  turkiyefinansnet:
    driver: bridge